### ISSUE TITLE
Loading DBpedia 2016-10

### ISSUE THREAD

**Issue by cbobed** [neo4j-labs/neosemantics#147]
Hi all, 

I've been trying to load DBpedia 2016-10 (the specific files are attached at the end of the post). However, it returns a KO, raising an exception in the parsing: 

Caused by: java.lang.IllegalArgumentException: datatype rdf:langString requires a language tag
        at org.eclipse.rdf4j.model.impl.SimpleLiteral.<init>(SimpleLiteral.java:94)
        at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createLiteral(AbstractValueFactory.java:116)
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.createLiteral(RDFParserHelper.java:194)
        ... 59 more

The kind of RDF triple that is causing this seems to be: 
 <http://dbpedia.org/resource/Autism> <http://xmlns.com/foaf/0.1/name> "Autism"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> .
 <http://dbpedia.org/resource/Alabama> <http://xmlns.com/foaf/0.1/name> "State of Alabama"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> .
 <http://dbpedia.org/resource/Alabama> <http://dbpedia.org/ontology/demonym> "Alabaman or Alabamian"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> .

Is there anywhere to relax a little the parser? I've tried using the validateUriSyntax parameter, but as it seems that it's the parser itself the one raising the exception. We had already processed this particular file using Jena without problems, just in case it would help.

Best

**Comment by cbobed** [comment]
Hi again, 

In the end, I've managed loading this version of DBpedia by first sed'ding the detected wrong values and changing the types of such strings to xsd:string (this changed about 200,000 triples, but problems arised afterwards with wrongly-formed URLs in the values, etc); and secondly, configuring the rdf4j rio parser via JVM params (I didn't remember it at the time I wrote the issue). 

For those who would be interested, I've tried using basic configuration parameters such as: 
#dbms.jvm.additional=-Dorg.eclipse.rdf4j.rio.verify_datatype_values=false
#dbms.jvm.additional=-Dorg.eclipse.rdf4j.rio.verify_language_tags=false

but it still broke with noisy types. For my purposes (I can afford losing some triples), I have used: 
dbms.jvm.additional=-Dorg.eclipse.rdf4j.rio.ntriples.fail_on_invalid_lines=false 

That configuration line should be added to the ./conf/neo4j.conf, of course. 

I close the issue as with that the relaxation required was achieved. 

Best,
