### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by YuzeLou** [neo4j-labs/neosemantics#164]
-  Neo4j Community Edition 4.0.6

- neosemantics 4.0.0.1

I was importing Wikidata N-Triple dump following neosemantics's README.

I got the following error in logs/neo4j.log:

```
java.lang.ClassCastException: class [D cannot be cast to class [Ljava.lang.Object; ([D and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
        at n10s.rdf.load.DirectStatementLoader.lambda$runPartialTx$2(DirectStatementLoader.java:76)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at n10s.rdf.load.DirectStatementLoader.runPartialTx(DirectStatementLoader.java:69)
        at n10s.rdf.load.DirectStatementLoader.periodicOperation(DirectStatementLoader.java:187)
        at n10s.RDFToLPGStatementProcessor.handleStatement(RDFToLPGStatementProcessor.java:416)
        at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:276)
        at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:154)
        at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:103)
        at n10s.CommonProcedures.instantiateAndKickOffParser(CommonProcedures.java:122)
        at n10s.CommonProcedures.parseRDFPayloadOrFromUrl(CommonProcedures.java:110)
        at n10s.rdf.RDFProcedures.doImport(RDFProcedures.java:77)
        at n10s.rdf.load.RDFLoadProcedures.fetch(RDFLoadProcedures.java:19)
        at org.neo4j.kernel.impl.proc.GeneratedProcedure_fetch1789451156021656.apply(Unknown Source)
        at org.neo4j.procedure.impl.ProcedureRegistry.callProcedure(ProcedureRegistry.java:208)
        at org.neo4j.procedure.impl.GlobalProceduresRegistry.callProcedure(GlobalProceduresRegistry.java:323)
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:941)
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallWrite(AllStoreHolder.java:858)
        at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.$anonfun$callReadWriteProcedure$2(CallSupport.scala:61)
        at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callProcedure(CallSupport.scala:97)
        at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callReadWriteProcedure(CallSupport.scala:62)
        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQueryContext.scala:821)
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.$anonfun$callReadWriteProcedure$1(ExceptionTranslatingQueryContext.scala:183)
        .......
```

This error only occurred  when `handleMultival` was set to "ARRAY".

**Comment by jexp** [comment]
Closing as stale. Reported against an old version of Neo4j (4.x or earlier) that is no longer supported. If still reproducible with current 5.x/2025.x + latest neosemantics, please open a new issue with full version details and a reproducible example.
