### ISSUE TITLE
InvalidCacheLoadException

### ISSUE THREAD

**Issue by YooSoYeon** [neo4j-labs/neosemantics#187]
When deleting large amounts of data with neoSemantics, the following error occurs. 
----------------------------------------------------------------------------------------------
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key http://kisti.re.kr/resource/BJD_1111010700.
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2375)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2337)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
----------------------------------------------------------------------------------------------
CacheLoader says that it cannot find a key and returns null,
 but when I search for that key in the store, the data exists.

**Comment by jbarrasa** [comment]
Hi, would it be possible to get some context, please?
Steps to reproduce the issue would be ideal.

Thanks,

JB.

**Comment by YooSoYeon** [comment]
Hi, I first import about 20G rdf file in neo4j using n10s.rdf.import.fetch
method.
Then, the imported data is deleted using the n10s.rdf.delete.fetch method.
However, InvalidCacheLoadException occurred in the process of deletion.

When I test in the same process with a small file, rdf data is imported and
deleted successfully.

2020년 9월 21일 (월) 오후 6:19, J. Barrasa <notifications@github.com>님이 작성:

**Comment by jbarrasa** [comment]
Do you mean you try to delete the whole file after loading it?
What’s the status of the DB after the failure? Are some triples deleted? Or none?
Any additional info in the logs? No stack trace?
Does this happen early in the process or after a while?
Is the 20GB RDF file public so we can try to reproduce?

Thanks,

JB

JB
________________________________

**Comment by YooSoYeon** [comment]
- Do you mean you try to delete the whole file after loading it?
*: yes, I delete the whole file after loading it.*
- What’s the status of the DB after the failure? Are some triples deleted?
Or none?
*: some triples deleted.*
-Does this happen early in the process or after a while?
*: this happen after a while.*
-Is the 20GB RDF file public so we can try to reproduce?
:* It's not a public file, so I need to discuss it for sharing.*

2020년 9월 22일 (화) 오후 4:53, J. Barrasa <notifications@github.com>님이 작성:

**Comment by jbarrasa** [comment]
I'll try it but it would be great if you could share your file. 
Let me know when you find out. You can send it privately to jesus at neo4j dot com

**Comment by YooSoYeon** [comment]
sorry for the late contact.
I received a notice that I can share the 20GB RDF file.
How do I share this file?



2020년 9월 24일 (목) 오전 4:52, J. Barrasa <notifications@github.com>님이 작성:

**Comment by jbarrasa** [comment]
That's great news.
Maybe you can put it somewhere I can download it from and then send me the access details and credentials to jesus at neo4j dot com ?

Thanks!

**Comment by YooSoYeon** [comment]
What does it mean to send credentials to jesus at neo4j dot com.

2020년 10월 13일 (화) 오후 5:40, J. Barrasa <notifications@github.com>님이 작성:

**Comment by jbarrasa** [comment]
send me by email the location and user/pwd if needed to download the file
that's my email address. Just replace   at=`@`  dot=`.` and you got it.

Thanks!

JB.

**Comment by YooSoYeon** [comment]
I send the file using the email ysyeon0503@naver.com.


2020년 10월 15일 (목) 오전 11:34, J. Barrasa <notifications@github.com>님이 작성:

**Comment by jexp** [comment]
Closing as stale. Reported against an old version of Neo4j (4.x or earlier) that is no longer supported. If still reproducible with current 5.x/2025.x + latest neosemantics, please open a new issue with full version details and a reproducible example.
